name: taskgenius
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Authentication & Storage
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  flutter_secure_storage: ^9.0.0

   # UI & Utils
  material_design_icons_flutter: ^7.0.7296
  intl: ^0.18.1
  uuid: ^4.2.1
  flutter_dotenv: ^5.1.0

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0
  
  # Drag & Drop
  flutter_reorderable_list: ^1.3.1
  get_it: ^8.0.3

  connectivity_plus: ^6.0.3
  flutter_slidable: ^3.1.1
  flutter_local_notifications: ^17.1.2

  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
