name: taskgenius
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  sqflite: ^2.3.3
  path_provider: ^2.1.1
  intl: ^0.18.1
  flutter_local_notifications: ^16.3.0
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
